### ISSUE TITLE
Can't select CSV

### ISSUE THREAD

**Issue by rome2o** [tannermeade/data-migrator#17]
Hi,

I tried to select a blank CSV file. We basically want to write from Appwrite to the CSV file e.g. taking a backup.

I failed to select CSV file on Web and MacOS as well

For MacOS

```
flutter: [backup_appwrite.csv]
flutter: /Volumes/Macintosh HD/Users/x/Desktop/backup_appwrite.csv
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Bad state: No element
#0      Stream.firstWhere.<anonymous closure> (dart:async/stream.dart:1399:9)
#1      _rootRun (dart:async/zone.dart:1418:47)
#2      _CustomZone.run (dart:async/zone.dart:1328:19)
#3      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#4      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
#5      _rootRun (dart:async/zone.dart:1418:47)
#6      _CustomZone.run (dart:async/zone.dart:1328:19)
#7      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:202:18)
#8      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:736:39)
#9      Future._propagateToListeners (dart:async/future_impl.dart:792:11)
#10     Future._completeWithValue (dart:async/future_impl.dart:601:5)
#11     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:639:7)
#12     _rootRun (dart:async/zone.dart:1426:13)
#13     _CustomZone.run (dart:async/zone.dart:1328:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)

```
For Web:
```
[backup_appwrite.csv]
Error:       On web `path` is always `null`,
      You should access `bytes` property instead,
      Read more about it [here](https://github.com/miguelpruivo/flutter_file_picker/wiki/FAQ)

    at Object.throw_ [as throw] (http://localhost:63669/dart_sdk.js:5067:11)
    at platform_file.PlatformFile.new.get path [as path] (http://localhost:63669/packages/file_picker/src/platform_file.dart.lib.js:78:19)
    at _pickFiles (http://localhost:63669/packages/data_migrator/infastructure/data_origins/csv_origin/csv_origin.dart.lib.js:308:68)
    at _pickFiles.next (<anonymous>)
    at http://localhost:63669/dart_sdk.js:40571:33
    at _RootZone.runUnary (http://localhost:63669/dart_sdk.js:40441:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:63669/dart_sdk.js:35363:29)
    at handleValueCallback (http://localhost:63669/dart_sdk.js:35931:49)
    at Function._propagateToListeners (http://localhost:63669/dart_sdk.js:35969:17)
    at _Future.new.[_completeWithValue] (http://localhost:63669/dart_sdk.js:35817:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:63669/dart_sdk.js:35838:35)
    at Object._microtaskLoop (http://localhost:63669/dart_sdk.js:40708:13)
    at _startMicrotaskLoop (http://localhost:63669/dart_sdk.js:40714:13)
    at http://localhost:63669/dart_sdk.js:36191:9
```

Any help would be much appreciated.

**Comment by tannermeade** [comment]
Hey @rome2o 👋 the app is still in very early alpha and in its current state, it doesn't support Appwrite to CSV. I've had to focus on work for the past while.
